---
title: "World Happiness Report Visualization"
output: html_notebook
---

In this R Notebook, I will attempt to visualize the 2015 World Happiness Repory using ggplot and ggflag. 

First, installing packages. 

```{r}
rm(list=ls())

if (!require("rworldmap")) {
  install.packages("rworldmap")
  library(rworldmap)
}

if (!require("countrycode")) {
  install.packages("countrycode")
  library(countrycode)
}


library(ggplot2)
library(tidyverse)
library(dplyr)
if (!require("ggflags")) {
  devtools::install_github("rensa/ggflags")
  library(ggflags)
}
```


Then load the data, 
```{r}
db15 <- read.csv("2015.csv", header = TRUE, stringsAsFactors = FALSE)
db15$Origin <- countrycode(c(db15$Country), "country.name", "iso2c")
db15$Origin <- tolower(db15$Origin)
```


I will first plot the GDP per Capita against the happiness score. 
```{r}
ggplot(db15,
       aes(x=Happiness.Score,
           y=Economy..GDP.per.Capita.),
           country=Origin)+
  geom_flag(country=db15$Origin,) +
  scale_country()
```




  